---
- name: gather facts
  setup:
    gather_timeout: 30

- name: 删除debian默认安装包
  apt: 
    name: 
      - ufw
      - lxd
      - lxd-client
      - lxcfs
      - lxc-common
    state: absent

- name: 安装debian基础软件
  apt: 
    name:
      - nfs-common          # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
      - conntrack           # network connection cleanup 用到
      - jq                  # 轻量JSON处理程序，安装docker查询镜像需要
      - socat               # 用于port forwarding
      - bash-completion     # bash命令补全工具，需要重新登录服务器生效
      - rsync               # 文件同步工具，分发证书等配置文件需要
      - ipset
      - ipvsadm
    state: present

- name: 设置 ulimits
  lineinfile:
    dest: /etc/profile
    regexp: "ulimit -SHn"
    line: "ulimit -SHn 65535"

# 优化设置 journal 日志相关，避免日志重复搜集，浪费系统资源
- name: 准备 journal 日志相关目录
  file: name={{ item }} state=directory
  with_items:
  - "/etc/systemd/journald.conf.d"
  - "/var/log/journal"

- name: 优化设置 journal 日志
  template: src=95-k8s-journald.conf.j2 dest=/etc/systemd/journald.conf.d/95-k8s-journald.conf

- name: 重启 journald 服务
  service: name=systemd-journald state=restarted

- name: setting absent kernel params
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    ignoreerrors: yes
    state: absent
  with_items:
    - { name: 'net.ipv4.tcp_tw_recycle', value: 0 }

- name: setting present kernel params
  sysctl: name="{{ item.name }}" value="{{ item.value }}" ignoreerrors=yes state=present
  with_items:
    - { name: 'net.core.somaxconn', value: 32768 }
    - { name: 'net.ipv4.tcp_syncookies', value: 0 }
    - { name: 'fs.file-max', value: 1000000 }
    - { name: 'vm.max_map_count', value: 655360 }
    - { name: 'net.netfilter.nf_conntrack_max', value: 1000000 }
    - { name: 'net.ipv4.ip_forward', value: 1 }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: 1 }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }
    - { name: 'net.bridge.bridge-nf-call-arptables', value: 1 }

- name: 加载内核模块
  modprobe: name={{ item }} state=present
  with_items:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
  ignore_errors: true

- name: 转换内核版本为浮点数
  set_fact:
     KERNEL_VER: "{{ ansible_kernel.split('-')[0].split('.')[0]|int + ansible_kernel.split('-')[0].split('.')[1]|int/100 }}"

- name: 加载内核模块 nf_conntrack
  modprobe: name=nf_conntrack state=present
  when: "KERNEL_VER|float >= 4.19"
  ignore_errors: true

- name: 加载内核模块 nf_conntrack_ipv4
  modprobe: name=nf_conntrack_ipv4 state=present
  when: "KERNEL_VER|float < 4.19"
  ignore_errors: true

- name: 启用systemd自动加载模块服务
  service: name=systemd-modules-load enabled=yes

- name: 增加内核模块开机加载配置
  template: src=10-k8s-modules.conf.j2 dest=/etc/modules-load.d/10-k8s-modules.conf

- name: update /etc/security/limits.conf
  blockinfile:
    dest: /etc/security/limits.conf
    insertbefore: '# End of file'
    block: |
        * soft nofile 1000000
        * hard nofile 1000000
        * soft stack 10240
        * soft nproc 65536
        * hard nproc 65536

- name: 把SCTP列入内核模块黑名单
  copy: src=sctp.conf dest=/etc/modprobe.d/sctp.conf
