baseURL = "https://ysicing.me"
languageCode = "zh-CN"
theme = "hello-friend"
themesDir = "themes"
title = "缘生笔记"

summaryLength = 140
hasCJKLanguage = true

# 每页显示的文章数量用于分页
paginate =  10
# rss 输出数量
rssLimit = 5
timeout = '30s'
ignoreErrors = ["error-remote-getjson","error-remote-getcsv"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  showPostsOnHomepage = true
  addDot = true
  baseColor = "var(--background-color)"
  baseOffsetColor = "#eaeaea"
  headingColor = "#000"
  dotColor = "var(--text-highlight-color)"

[permalinks]
  posts = '/posts/:filename/'

[params.artalk]
    server="https://artalk.ysicing.cloud"
    site="缘生笔记"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[outputs]
  home = ["Atom", "HTML","JSON"] # <domain>/atom.xml
  page = ["HTML"]

[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 1
