FROM ysicing/openresty

ENV TZ Asia/Shanghai

COPY ./public /var/www/ysicing.me/public

COPY scripts/hugo/default.conf /etc/nginx/conf.d/default.conf


CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]


