---
kind: pipeline
type: exec
name: default

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone git@code.devops.ysicing.net:ysicing/devops-handbook.git
- name: push github
  commands:
  - git remote add github git@github.com:ysicing/devops-handbook.git
  - git push github master
  when:
    event:
    - cron