---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    k8s.godu.dev/name: mysql
  name: cloud-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.godu.dev/name: mysql
  serviceName: cloud-mysql
  template:
    metadata:
      labels:
        k8s.godu.dev/name: mysql
    spec:
      containers:
        -
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '12345678'
          image: 'mysql:5.6.41'
          imagePullPolicy: Always
          name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
              readOnly: false
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        annotations:
          k8s.eip.work/pvcType: Dynamic
        name: mysql
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
        storageClassName: nfs-test

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s.godu.dev/name: mysql
  name: cloud-mysql
  namespace: default
spec:
  ports:
    - name: yidtyn
      nodePort: 0
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    k8s.godu.dev/name: mysql
  type: ClusterIP


