# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.provider 'virtualbox' do |vb|
   vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
  end  
  config.vm.synced_folder ".", "/src", type: "nfs", nfs_udp: false
  $num_instances = 1
  (1..$num_instances).each do |i|
    config.vm.define "godu#{i}" do |node|
      node.vm.box = "ysicing/debian"
      node.vm.box_version = "9.11.0"
      node.vm.hostname = "godu#{i}"
      ip = "10.8.82.#{i+34}"
      node.vm.network "private_network", ip: ip
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "8000"
        vb.cpus = 4
        vb.name = "godu#{i}"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        # cpu 使用率50%
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      end
    end
  end
end
