apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
    address-pools:
    - name: lbpool
      protocol: layer2
      addresses:
      - 10.0.0.6/32
      - 10.0.0.8/32
      - 10.0.0.13/32