#!/bin/bash

pushd /tmp

wget https://github.techoc.workers.dev/https://github.com/containerd/nerdctl/releases/download/v0.12.1/nerdctl-full-0.12.1-linux-amd64.tar.gz
tar Cxzvvf /usr/local nerdctl-full-0.12.1-linux-amd64.tar.gz
rm -rf nerdctl-full-0.12.1-linux-amd64.tar.gz
popd 

systemctl enable containerd.service --now

cat > /usr/local/bin/docker <<EOF
#!/bin/bash
/usr/local/bin/nerdctl $@
EOF

chmod +x /usr/local/bin/docker
docker run --rm -v /usr/local/bin:/sysdir registry.cn-beijing.aliyuncs.com/k7scn/tools tar zxf /pkg.tgz -C /sysdir
