name: deloy ysicing.me
on:
  push:
    branches:
    - master

jobs:
  build:
    name: build & deploy
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: build
      run: |
          make build
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ysicing/devops-handbook -f scripts/gitbook/Dockerfile.nginx .
          docker push ysicing/devops-handbook
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_book
    - name: deploy to k8s
      run: |
          docker pull ysicing/devops-handbook
          docker tag ysicing/devops-handbook ysicing/devops-handbook:$(date +%F-%H)
          docker push ysicing/devops-handbook:$(date +%F-%H)
          bash scripts/gitbook/deploy.sh $TOKEN $APIURL ysicing/devops-handbook:$(date +%F-%H)