name: deloy 2021.ysicing.me
on:
  push:
    branches:
    - 2021
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: build
      run: |
          make build
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ysicing/devops-handbook:2021 -f scripts/gitbook/Dockerfile.nginx .
          docker push ysicing/devops-handbook:2021
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_book
