name: deloy ysicing.me
on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    name: build & deploy
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
        submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.68.3'
        extended: true        
    - name: build
      run: |
          hugo --minify
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ysicing/devops-handbook -f scripts/hugo/Dockerfile.nginx .
          docker push ysicing/devops-handbook
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: deploy to k8s
      run: |
          docker pull ysicing/devops-handbook
          ver=$(date +%s)
          docker tag ysicing/devops-handbook ysicing/devops-handbook:$ver
          docker push ysicing/devops-handbook:$ver
          bash scripts/hugo/deploy.sh $TOKEN $APIURL ysicing/devops-handbook:$ver
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        TOKEN: ${{ secrets.TOKEN }}
        APIURL: ${{ secrets.APIURL }}
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public