name: douban
on:
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: ysicing
        type: movie
        format: csv
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: ysicing
        type: book
        format: csv
        dir: ./data/douban

    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore: update douban data'
        add: './data/douban'
