name: deloy sh.ysicing.me
on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 5 */1 * *'

jobs:
  build:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Login GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: Login Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build
      run: |
          docker build -t ysicing/devops-handbook:sh.ysicing.me -f scripts/caddy/sh.ysicing.me/Dockerfile .
          docker push ysicing/devops-handbook:sh.ysicing.me
          docker tag ysicing/devops-handbook:sh.ysicing.me ghcr.io/ysicing/devops-handbook:sh.ysicing.me
          docker push ghcr.io/ysicing/devops-handbook:sh.ysicing.me
