name: deloy ysicing.me
on:
  push:
    branches:
    - master

jobs:
  build:
    name: build & deploy
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: Login Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: build
      run: |
          sed -i "s#wiki.ysicing.me#ysicing.me#g" docusaurus.config.js
          sed -i "s#your-website-id#4c49e691-9efd-4049-ba15-fac0e5a34ea6#g" docusaurus.config.js
          sed -i "s#京ICP##g" docusaurus.config.js
          mv data/Invitelink.ts.hk data/Invitelink.ts
          hugo --minify
          docker build -t ysicing/devops-handbook:2023hugo -f scripts/caddy/ysicing.me/Dockerfile .
          docker push ysicing/devops-handbook:2023hugo
          docker tag ysicing/devops-handbook:2023hugo ghcr.io/ysicing/devops-handbook:2023hugo
          docker push ghcr.io/ysicing/devops-handbook:2023hugo

