name: deloy ysicing.me
on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    name: build & deploy
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
        submodules: true
    - name: Login GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCRIO }}
    - name: Login Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'
        extended: true        
    - name: build
      run: |
          rm -rf config/_default/params.toml
          rm -rf config/_default/config.toml
          cp -a scripts/config/ysicing.me.toml config/_default/config.toml
          cp -a scripts/config/ysicing.me.params.toml config/_default/params.toml
          hugo --minify
          docker build -t ysicing/devops-handbook:ysicing.me -f scripts/caddy/ysicing.me/Dockerfile .
          docker push ysicing/devops-handbook:ysicing.me
          docker tag ysicing/devops-handbook:ysicing.me ghcr.io/ysicing/devops-handbook:ysicing.me
          docker push ghcr.io/ysicing/devops-handbook:ysicing.me

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public